name: Build and Push to Builds Repo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_EMAIL: adam.jimenez@gmail.com
      MY_NAME: adamjimenez
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Push to Builds Repo
        run: |
          git config user.email "$MY_EMAIL"
          git config user.name "$MY_NAME"
          git add .
          git commit -m 'Deploying latest build'
          git remote set-url origin https://$MY_NAME:${{ secrets.SSH_KEY }}@github.com/adamjimenez/shiftedit-builds.git
          git push origin master